version: '3'

services:
  front-end:
    build: .
    image: front-end
    container_name: front-end
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - infrastructure_default

networks:
  infrastructure_default:
    external: true
