name: CI
on:
  push:
    branches: ["develop"]

jobs:
  build:
    name: build packages
    runs-on:
      - gpt-4
    steps:
      - uses: actions/checkout@v3
      - name: build packages
        run: |
          echo "VITE_PUBLIC_DEFAULT_API==https://backend-api.umuganda.digital/api/v1" > .env.local
          docker compose down -v || true
          docker compose build
          docker compose up -d
