name: CI
on:
  push:
    branches: ["develop"]

jobs:
  build:
    name: build packages
    runs-on:
      - gpt-4
    steps:
      - uses: actions/checkout@v3
      - name: build packages
        run: |
          docker compose down -v || true
          docker compose build
          docker compose up -d
