name: CI
on:
  push:
    branches: ["develop"]

jobs:
  build:
    name: build packages
    runs-on:
      - gpt-4
    steps:
      - uses: actions/checkout@v3
      - name: build packages
        run: |
          yarn install
          yarn build
